language: python
python:
    - "2.7"
#    - "3.4"
sudo: required
addons:
  apt:
    packages:
    - build-essential
    - automake
    - autoconf
    - libtool
    - python-dev
    - libxml++2.6-dev
    - swig
install:
    - svn checkout svn://svn.code.sf.net/p/ghmm/code/trunk/ghmm ghmm_
    - cd ghmm
    - sh autogen.sh
    - sudo ./configure
    - sudo make
    - sudo make install
    - sudo ldconfig
    - cd ..
    - ln -s ghmm ghmm_/ghmmwrapper

script:
    - py.test