language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - pip install pytest pytest-cov numpy
    - svn checkout svn://svn.code.sf.net/p/ghmm/code/trunk/ghmm ghmm
    - cd ghmm
    - ./autogen.sh
    - ./configure
    - make
    - make install
script:
    - py.test